"""Paper-only order tickets and fill accounting."""

from shm.paper.core import (
    FILL_COLUMNS,
    FILL_OPTIONAL_COLUMNS,
    PAPER_MODE,
    PAPER_LOOKBACK_SESSIONS,
    TICKET_COLUMNS,
    AppliedFill,
    Fill,
    FillIngestionResult,
    MonthlyComparisonInputs,
    OrderTicket,
    PaperAccount,
    SkippedCandidate,
    TicketPlan,
    build_monthly_comparison_inputs,
    fills_from_frame,
    fills_to_frame,
    generate_integer_share_tickets,
    ingest_fills,
    paper_xnys_window,
    read_fill_csv,
    read_ticket_csv,
    realized_cost_bps,
    render_monthly_report,
    require_paper_mode,
    tickets_from_frame,
    validate_paper_window,
    write_fill_csv,
    write_monthly_report,
    write_ticket_csv,
)
from shm.paper.runner import PaperRebalanceResult, run_paper_rebalance
from shm.paper.simulator import SimulatedFillResult, simulate_next_open_fills

__all__ = [
    "FILL_COLUMNS",
    "FILL_OPTIONAL_COLUMNS",
    "PAPER_MODE",
    "PAPER_LOOKBACK_SESSIONS",
    "TICKET_COLUMNS",
    "AppliedFill",
    "Fill",
    "FillIngestionResult",
    "MonthlyComparisonInputs",
    "OrderTicket",
    "PaperAccount",
    "PaperRebalanceResult",
    "SkippedCandidate",
    "SimulatedFillResult",
    "TicketPlan",
    "build_monthly_comparison_inputs",
    "fills_from_frame",
    "fills_to_frame",
    "generate_integer_share_tickets",
    "ingest_fills",
    "paper_xnys_window",
    "read_fill_csv",
    "read_ticket_csv",
    "realized_cost_bps",
    "render_monthly_report",
    "require_paper_mode",
    "run_paper_rebalance",
    "simulate_next_open_fills",
    "tickets_from_frame",
    "validate_paper_window",
    "write_fill_csv",
    "write_monthly_report",
    "write_ticket_csv",
]
